apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml

labels:
  - pairs:
      app.kubernetes.io/name: mock-dcgm-exporter-mig
    includeSelectors: true

images:
  - name: mock-dcgm-exporter-mig
    newName: mock-dcgm-exporter-mig
    newTag: latest
